@echo off
echo:   
echo This script calls C:\Xilinx\Vivado\2018.2\bin\updatemem.bat to edit a .bit file
echo with data from a .mem file generated by _hex2mem3.exe from BLINKY.hex in Keil
echo  -its .mmi argument must be customized to match the BRAMs location in the FPGA
echo  -its .mem argument is derived from the compiled 8051 code in .\8051_code\BLINKY.hex
echo  -its .bit input is generated by Vivado in ..\project_2.runs\impl_1\top.bit 
echo  -its .bit output is the new FPGA configuration file .\newtop.bit
pause
echo:  
REM Following path-setting copies those which precede Vivado's startup 
REM CALL C:\Xilinx\Vivado\2018.2\.settings64-Vivado.bat
SET PATH=C:\Xilinx\Vivado\2018.2\bin;C:\Xilinx\Vivado\2018.2\lib\win64.o;%PATH%
SET XILINX_VIVADO=C:\Xilinx\Vivado\2018.2

REM CALL C:\Xilinx\DocNav\.settings64-DocNav.bat
SET PATH=C:\Xilinx\DocNav;%PATH%

REM CALL C:\Xilinx\SDK\2018.2\.settings64-SDK_Core_Tools.bat
SET PATH=C:\Xilinx\SDK\2018.2\bin;C:\Xilinx\SDK\2018.2\gnu\microblaze\nt\bin;C:\Xilinx\SDK\2018.2\gnu\arm\nt\bin;C:\Xilinx\SDK\2018.2\gnu\microblaze\linux_toolchain\nt64_le\bin;C:\Xilinx\SDK\2018.2\gnu\aarch32\nt\gcc-arm-linux-gnueabi\bin;C:\Xilinx\SDK\2018.2\gnu\aarch32\nt\gcc-arm-none-eabi\bin;C:\Xilinx\SDK\2018.2\gnu\aarch64\nt\aarch64-linux\bin;C:\Xilinx\SDK\2018.2\gnu\aarch64\nt\aarch64-none\bin;C:\Xilinx\SDK\2018.2\gnu\armr5\nt\gcc-arm-none-eabi\bin;C:\Xilinx\SDK\2018.2\tps\win64\cmake-3.3.2\bin;C:\Xilinx\SDK\2018.2\gnuwin\bin;%PATH%
echo:   
echo clean previous work (if any)
del BLINKY.mem
del newtop.bit
echo:   
echo translate .hex file into .mem file
_hex2mem3 ..\8051_code\BLINKY.hex BLINKY.mem
echo:  
echo insert .mem file into .bit file 
call C:\Xilinx\Vivado\2019.2\bin\updatemem.bat -meminfo 4Kx8_X0Y3_bram.mmi -data BLINKY.mem -proc dummy -bit  ..\..\project_2.runs\impl_2\top.bit -out newtop.bit -force -debug
echo:
echo review results
pause
