@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Feb 20 14:58:46 -0500 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim top_top_sch_tb_behav -key {Behavioral:sim_1:Functional:top_top_sch_tb} -tclbatch top_top_sch_tb.tcl -view C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sim_1/imports/0925_Vivado+uVision_project_2/ROM_address-data_top_top_sch_tb_func_synth.wcfg -log simulate.log"
call xsim  top_top_sch_tb_behav -key {Behavioral:sim_1:Functional:top_top_sch_tb} -tclbatch top_top_sch_tb.tcl -view C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sim_1/imports/0925_Vivado+uVision_project_2/ROM_address-data_top_top_sch_tb_func_synth.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
