webtalk_init -webtalk_dir C:/_umd/_2018-09-01/445_F18/_work/0925_Vivado+uVision_project_2/project_2.sim/sim_1/synth/func/xsim/xsim.dir/top_top_sch_tb_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Sep 26 16:31:23 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "93ac38688dfa56f68f47ca4c9959cbfa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6c1db3e343364d959d120b02e9897da1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3193 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "40001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "31.37_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "27580_KB" -context "xsim\\usage"
webtalk_transmit -clientid 170265854 -regid "" -xml C:/_umd/_2018-09-01/445_F18/_work/0925_Vivado+uVision_project_2/project_2.sim/sim_1/synth/func/xsim/xsim.dir/top_top_sch_tb_func_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/_umd/_2018-09-01/445_F18/_work/0925_Vivado+uVision_project_2/project_2.sim/sim_1/synth/func/xsim/xsim.dir/top_top_sch_tb_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/_umd/_2018-09-01/445_F18/_work/0925_Vivado+uVision_project_2/project_2.sim/sim_1/synth/func/xsim/xsim.dir/top_top_sch_tb_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
