@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Sep 26 12:15:51 -0400 2018
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim top_top_sch_tb_func_synth -key {Post-Synthesis:sim_1:Functional:top_top_sch_tb} -tclbatch top_top_sch_tb.tcl -view C:/_umd/_2018-09-01/445_F18/_work/0925_Vivado+uVision_project_2/project_2.srcs/sim_1/imports/0925_Vivado+uVision_project_2/ROM_address-data_top_top_sch_tb_func_synth.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
