# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.cache/wt [current_project]
set_property parent.project_path C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.8051/tools/BLINKY.mem
read_verilog -library xil_defaultlib {
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/new/ClkDivider.v
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/LUT_RAM_from_template02.v
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/ROM4Kx8.v
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/top_nosch_01.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/mc8051_p.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/addsub_core_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/addsub_core_struc.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/addsub_cy_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/addsub_cy_rtl.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/addsub_ovcy_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/addsub_ovcy_rtl.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/alucore_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/alucore_rtl.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/alumux_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/alumux_rtl.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/comb_divider_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/comb_divider_rtl.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/comb_mltplr_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/comb_mltplr_rtl.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/control_fsm_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/control_fsm_rtl.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/control_mem_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/control_mem_rtl.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/dcml_adjust_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/dcml_adjust_rtl.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/mc8051_alu_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/mc8051_alu_struc.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/mc8051_control_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/mc8051_control_struc.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/mc8051_core_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/mc8051_core_struc.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/mc8051_siu_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/mc8051_siu_rtl.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/mc8051_tmrctr_.vhd
  C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/sources_1/imports/8051_logic/mc8051_tmrctr_rtl.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/constrs_1/imports/8051_logic/project_2/8051_P0_P1_only.xdc
set_property used_in_implementation false [get_files C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/constrs_1/imports/8051_logic/project_2/8051_P0_P1_only.xdc]

read_xdc C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/constrs_1/new/8051_P0_P1_2.xdc
set_property used_in_implementation false [get_files C:/Users/abhinav8/Downloads/Vivado+uVision_project_2/project_2.srcs/constrs_1/new/8051_P0_P1_2.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35ticpg236-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
